### ISSUE TITLE
[docs] Update README

### ISSUE THREAD

**Issue by codesankalp** [codesankalp/dsalgo#17]
Now we are ready to release a starting version of this package. So to make it understandable to other users it is required to have a good readme. 

* While writing readme it is required to think like you have never used this code and you are a complete beginner.
* readme extension must be __.rst__ because it will also be available on PyPI.

The basic idea of this repository is to create reusable functions for ds and algo so that users don't need to rewrite the same piece of code again and again.

**Comment by viveksahu26** [comment]
Hey @KapilBansal320  , is this work open for first time user or new contributer. Then i would like to work on it..

**Comment by KapilBansal320** [comment]
@viveksahu26 you can work on this. Assigning you for this.

**Comment by viveksahu26** [comment]
@KapilBansal320  .Thanks for assigning..

**Comment by devkapilbansal** [comment]
@viveksahu26 remember to post regular updates here. As issue can be unassigned due to inactivity.

**Comment by viveksahu26** [comment]
@devkapilbansal , Ok.. But I have taken this for hactoberfest.

**Comment by devkapilbansal** [comment]
> @devkapilbansal , Ok.. But I have taken this for hactoberfest.

You should ask for assignment only when you are going to work on it.

**Comment by viveksahu26** [comment]
@devkapilbansal , but i was working on it. Though i would have send pr after 1 october.

**Comment by devkapilbansal** [comment]
> @devkapilbansal , but i was working on it. Though i would have send pr after 1 october.

Okay I am assigning you for this again . But in future remember to make a pull request soon or at least update the challenges you are facing for that.

**Comment by viveksahu26** [comment]
ok..

**Comment by devkapilbansal** [comment]
@viveksahu26 are you still working on this?

**Comment by devkapilbansal** [comment]
Unassigning due to inactivity.
