### ISSUE TITLE
Improve contributing.md

### ISSUE THREAD

**Issue by devkapilbansal** [codesankalp/dsalgo#36]
## Description
After reviewing some pull requests, I realised that we don't have strict guidelines in contributing files. Here are some changes I would suggest: 

- We should use conventional commit guidelines. This link may help https://www.conventionalcommits.org/en/v1.0.0/

We can add a commit template later for this

- Before working on an issue, you should get it assigned.

- If an issue is assigned to you, be sure to post updates. Otherwise, the assignee would be removed after 3 days of inactivity

- You should make a branch other than the default branch for the pull request.

**Comment by Aryamanz29** [comment]
Hey, I'm interested in working on this issue could you assign this to me.

**Comment by codesankalp** [comment]
Ok @Aryamanz29  assigning you this issue.
Happy coding 🙂.
