### ISSUE TITLE
Insert an item in front of a doubly linked list

### ISSUE THREAD

**Issue by keshavgbpecdelhi** [codesankalp/dsalgo#77]
Currently there is a `doubly_linked_list.py` file in dsalgo (not merged yet) folder but there is no way to insert an item in front of a given doubly linked list for example, if function name is `insert_start()` (this is preferred name) 

then:
- [ ] code for which items.insert_start([_this contains required object_]) will show up the new object added in front of the doubly linked list created previously in continuation with issue #67 
- [ ] make a pull request for queue branch not for master branch.
- [ ] update the queue branch with the master.

P.S : Refer [this](https://github.com/codesankalp/dsalgo/pull/57/commits/a9e3e248d7d5745b00661f46ed5324c9f0ea17e2) commit for doubly_linked_list.py file. 
or the issue #56 in continuation with issue #67

**Comment by dennis-pg** [comment]
Can look into this

**Comment by keshavgbpecdelhi** [comment]
@dennis-pg go ahead 👍
